project:
  name: pdftotext++
  description: A super duper description.

  maintainer:
    name: Claudius Korzen
    mail: korzen@cs.uni-freiburg.de

  requirements:
    # The packages required to execute the Makefile target 'checkstyle'.
    checkstyle:
      apt: python3
      other:
    # The packages required to execute the Makefile target 'compile'.
    compile:
      apt: build-essential git cmake libboost-all-dev libfontconfig1-dev libfreetype6-dev libnss3-dev libopenjp2-7-dev libtiff5-dev
      other:
        tensorflow: ./install_requirements.sh install_tensorflow
        cppflow: ./install_requirements.sh install_cppflow
        poppler: ./install_requirements.sh install_poppler
        utf8proc: ./install_requirements.sh install_utf8proc
    # The packages required to run the project on any machine (without compiling the project).
    run:
      apt: libboost-all-dev libfontconfig1-dev libfreetype6-dev libnss3-dev libopenjp2-7-dev libtiff5-dev
    # The packages required to execute the Makefile target 'test' (extends from compile).
    test:
      apt:
      other:
        gtest: ./install_requirements.sh install_gtest
    # The packages required to execute the Makefile target 'install' (extends from compile).
    install:
      apt:
      other:
    # The packages required to execute the Makefile target 'packages' (extends from compile).
    packages:
      apt: tar lsb-release wget
      other:

  package:
    dists:
      - name: ubuntu2004-amd64
        Dockerfile: Dockerfiles/Dockerfile.package.ubuntu2004-amd64

      - name: ubuntu2204-amd64
        Dockerfile: Dockerfiles/Dockerfile.package.ubuntu2204-amd64