FROM pdftotextplusplus/base:ubuntu-20.04

LABEL maintainer="Claudius Korzen <korzen@cs.uni-freiburg.de>"

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV LC_CTYPE C.UTF-8
ENV DEBIAN_FRONTEND=noninteractive

ENTRYPOINT ["/bin/bash"]

RUN apt-get update && apt-get install -y gdb

# ==================================================================================================
# USEFUL COMMANDS

# BUILDING DOCKER IMAGE:
# docker build -f ./Dockerfiles/Dockerfile.ubuntu:20.04.dev -t pdftotext-plus-plus-dev .

# STARTING DOCKER CONTAINER:
# docker run --rm -it -v $(pwd):/pdftotext pdftotext-plus-plus-dev
