FROM pdftotextplusplus/base:ubuntu-18.04

LABEL maintainer="Claudius Korzen <korzen@cs.uni-freiburg.de>"

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV LC_CTYPE C.UTF-8
ENV DEBIAN_FRONTEND=noninteractive

# ==================================================================================================

COPY src src
COPY test test
COPY cpplint.py cpplint.py
COPY CPPLINT.cfg CPPLINT.cfg
COPY Makefile.Docker Makefile
RUN make install

ENTRYPOINT ["pdftotext++"]

# ==================================================================================================
# USEFUL COMMANDS

# BUILDING DOCKER IMAGE:
# docker build -t pdftotext-plus-plus .

# EXTRACTING TEXT FROM A SINGLE PDF:
# docker run --rm -v <path-to-pdf>:/file.pdf pdftotext-plus-plus /file.pdf -
