name: checkstyle

on:
  push:
    branches: [ master ]

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install requirements
        run: |
          sudo make requirements/checkstyle

      - name: make checkstyle
        run: |
          make checkstyle