name: checkstyle

on:
  push:
    branches: [ master ]

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install python3
        run: |
          make requirements/pre
          make requirements/checkstyle

      - name: make checkstyle
        run: |
          make checkstyle