name: unit_test

on: push

jobs:
  unit_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: installing requirements
        run: |
          sudo make requirements/unit-test USR_DIR="/usr/local"

      - name: running unit tests
        run: |
          make unit-test USR_DIR="/usr/local"

