name: unit_test

on: push

jobs:
  unit_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install requirements
        run: |
          sudo apt install -y build-essential cmake git tar wget
          wget https://github.com/mikefarah/yq/releases/download/v4.32.2/yq_linux_amd64 -O /usr/bin/yq && chmod +x /usr/bin/yq
          RUN make requirements/pre
          RUN make requirements/run
          RUN make requirements/test

      - name: make test
        run: |
          make test

