name: unit_test

on: push

jobs:
  unit_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install requirements
        run: |
          sudo apt install -y build-essential cmake git tar wget
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.32.2/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq
          sudo make requirements/pre USR_DIR="/usr/local"
          sudo make requirements/run USR_DIR="/usr/local"
          sudo make requirements/test USR_DIR="/usr/local"
          sudo ldconfig

      - name: make test
        run: |
          make test USR_DIR="/usr/local"

