name: unit_test

on: push

jobs:
  unit_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install requirements
        run: |
          apt update
          apt install -y make
          make requirements/pre USR_DIR="/usr/local"
          make requirements/test USR_DIR="/usr/local"

      - name: make test
        run: |
          make test USR_DIR="/usr/local"

